### ISSUE TITLE
on WSL/Windows 11, thread 'main' panicked

### ISSUE THREAD

**Issue by Ludorg** [hexroll/hexroll3#2]
After compilation, on WSL/Windows 11, I've got an error on startup:
```
thread 'main' panicked at hexroll3-testbed/src/app.rs:101:57:
```

By replacing the faulty line
```rust
.initial_directory(dirs::document_dir().unwrap())
```

with a path to my hardcoded home directory, the testbed starts.
```rust
.initial_directory(std::path::PathBuf::from("/home/ludorg"))
```

PS: great job and thank you for sharing your code 👍

**Comment by hexroll** [comment]
Thank you! Happy to share.
I added a fallback to home_dir() in Commit 272a435. Hopefully this will fix it.
